### ISSUE TITLE
cpus() is incorrect in containers

### ISSUE THREAD

**Issue by jdmarshall** [VeXell/pm2-autoscale#1]
You'll want to use availableParallelism to determine how many cores you can access, versus how many you can see.

cgroups doesn't have a way to hide CPUs, and docker does nothing to simulate it. 

Your code will behave especially badly on Docker Desktop.

**Comment by VeXell** [comment]
@jdmarshall Hi. Thank you for your comment. Do you have an example please? Or how do you run the container ?
I tested it on mac and we run it in production on linux and in general `os.cpus().length` shows correct information about available cpus.

**Comment by VeXell** [comment]
@jdmarshall I have updated my code to use `availableParallelism` from `node:os` module which is available only from node 18.18. In other case i will use cpu length or use `nproc`.
