### ISSUE TITLE
The app is not scaling 

### ISSUE THREAD

**Issue by ashkraba** [VeXell/pm2-autoscale#3]
Hello coleagues,

Could you please assist me with the next issue:
I am starting the app with the next ecosystemconfig file:
```module.exports = {
  apps: [
    {
      name: "dev-prestigioplaza-kz",
      exec_mode: 'cluster',
      instances: 1, // Or a number of instances
      script: "/storage/data/nginx/sites/node_modules/nuxt/bin/nuxt.js",
      args: 'start /storage/data/nginx/sites/dev-prestigioplaza-kz.webplatform.webdev.it4profit.biz',
      out_file: "/storage/logs/pm2/dev-prestigioplaza-kz.webplatform.webdev.it4profit.biz_out.log",
      error_file: "/storage/logs/pm2/dev-prestigioplaza-kz.webplatform.webdev.it4profit.biz_error.log",
      merge_logs: true,
      time: true,
      max_restarts: 5,
    },
  ]
}
```
But my application is not scaling, even if is used more the 100% of CPU, it continue to increase memory use.
I have manually set
```
pm2 set pm2-autoscale:debug true
pm2 set pm2-autoscale:scale_cpu_threshold 50
```
But I haven't seen any logs in `pm2 logs` output, what I am doing wrong. 
```
root@dev:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@dev:~# npm list -g | grep pm2
├── pm2-autoscale@1.0.5
├── pm2@5.3.0
```
The VM has enough memory:
```
root@dev:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           3.9Gi       2.3Gi       209Mi       1.0Mi       1.4Gi       1.3Gi
```
Thanks a lot in advance.

**Comment by ashkraba** [comment]
I have updated it to the latest version, but have the same results
```
root@wpl-front-plaza-dev:~# npm list -g | grep pm2
├── pm2-autoscale@1.2.1
├── pm2@5.3.0
```

**Comment by VeXell** [comment]
Hello @ashkraba  can you show me logs with command `pm2 log pm2-autoscale` (and enable debug with command `pm2 set pm2-autoscale:debug true` before) especially when your CPU is increasing. And also `pm2 status` screenshot if you can. An show `cat /proc/cpuinfo`or `nproc` output. Thank you. 

I guess the problem with not enough free memory for new app instance.

**Comment by ashkraba** [comment]
Hello Viacheslav(@VeXell)! Thanks a lot for your responce.
```
root@dev:~# nproc
4
```
```
root@dev:~# pm2 set pm2-autoscale:debug true
[PM2] Setting changed
Module: pm2-autoscale
$ pm2 set pm2-autoscale:debug true
$ pm2 set pm2-autoscale:scale_cpu_threshold 10
root@dev:~# pm2 logs auto-scaler
[TAILING] Tailing last 15 lines for [auto-scaler] process (change the value with --lines option)

```
Even with these settings the output of `pm2 log pm2-autoscale` is empty.
But at the same time when I using `pm2 monit` I could see temporary cpu load 60%.
The main problem that when I am using 
`ab -n 6000 -c 10 https://my_url/` I could see the increasing of the CPU and memory for the process until OOM, but not scaling.
![Screenshot 2024-02-10 at 11 49 19](https://github.com/VeXell/pm2-autoscale/assets/61412809/4c5bcaa7-3152-4bc1-afbd-ac264d9b2777)
May be I have missed something to enable this feature.

**Comment by VeXell** [comment]
Hello @ashkraba

You entered wrong command for logs. Instead of `pm2 logs auto-scaler` it should be `pm2 log pm2-autoscale`. This is the reason why you do not see any logs. 

With correct output you should see the reason of the problem i hope.

**Comment by ashkraba** [comment]
Hello @VeXell . Thanks, but the same result.(
```
root@dev:~# pm2 log pm2-autoscale
[TAILING] Tailing last 15 lines for [pm2-autoscale] process (change the value with --lines option)

```

**Comment by ashkraba** [comment]
Should I somehow enable this feature in ecosystemconfig?

**Comment by ashkraba** [comment]
The app has the next params.
```
App Name              test.app
Namespace             default
Version               2.15.8
Script path           /storage/data/nginx/sites/node_modules/nuxt/bin/nuxt.js
Script args           start /storage/data/nginx/sites/test.app
Interpreter           node
Interpreter args      N/A
Exec mode             cluster
Node.js version       16.20.2
watch & reload        ✘
```

**Comment by ashkraba** [comment]
And could you please clarify how long should be the cpu utilization to start auto-scale?
Thanks a lot.

**Comment by VeXell** [comment]
@ashkraba Can you show me full screenshot on `pm2 status` command? Or do you see `pm2-autoscale` plugin running (you should install it with command `pm2 install pm2-autoscale`)? 

It should run autoscaling when CPU load increase `scale_cpu_threshold`. For example in your case 10% of CPU load. 

No. you should not enable anything in `ecosystem`. 

Also you should see logs from the module every 10 sec new output.

**Comment by ashkraba** [comment]
Appreciate your help @VeXell !

Looks like it was the root cause of the issue. I have installed it with `npm install -g pm2-autoscale`. Now I have seen the logs and the enabled module in the status output.
Thanks a lot for your help and so incredible feature. 

Regards!

**Comment by VeXell** [comment]
@ashkraba You are welcome. Let me know if you face any other problems.
Star the repo if you like it. Thank you.
