### ISSUE TITLE
Question: Can the pm2-autoscale settings be set via the ecosystem configuration file (e.g. per-application)?

### ISSUE THREAD

**Issue by hostalp** [VeXell/pm2-autoscale#4]
We're currently evaluating the possibilities to auto-scale NodeJS applications and have found this module to be potentially suitable.
However the documentation (as well at the more complete article https://vexell.medium.com/autoscale-node-js-applications-with-pm2-and-pm2-autoscale-module-3129582dc72c) appears to mention the possibility to apply the auto-scaling settings (scale_cpu_threshold, release_cpu_threshold) only globally.

We'd like to be able to set these per-application so that different applications can use different settings. Is it (or will it be) possible?

There are some workarounds that come to our minds, however we'd really prefer the straightforward approach - just setting these parameters in the .config.js file or so.

**Comment by VeXell** [comment]
Hello @hostalp Thank you for you message. Yes, this is a good point. I guess the best place for that might be ecosystem config file. I will think how i can get access for that in the module (if it possible to use custom properties).

**Comment by VeXell** [comment]
Hello @hostalp 

Have a look on the pull request and readme file https://github.com/VeXell/pm2-autoscale/pull/5
Does it work for you?

It allows you to change settings per app with providing env string

**Comment by VeXell** [comment]
Merged to main and published with new version 1.3.1

**Comment by hostalp** [comment]
Yes this looks good. 👍

**Comment by VeXell** [comment]
@hostalp Thank you. I will appreciate if you star my repo.
